# Use and existing Julia image as a base
FROM rocm/dev-ubuntu-24.04:6.3 AS builder

ENV JULIA_DEPOT_PATH=/opt/julia-depot

RUN wget https://julialang-s3.julialang.org/bin/linux/x64/1.12/julia-1.12.7-linux-x86_64.tar.gz
RUN tar -xzf julia-1.12.7-linux-x86_64.tar.gz
ENV PATH="/julia-1.12.7/bin:${PATH}"

COPY . /dftk_source
WORKDIR /dftk_source

# Add AMDGPU package to the project environment TODO: is that necessary?
RUN julia --project="/dftk_source/TestEnv" -e '\
    using Pkg; \
    Pkg.add("AMDGPU"); \
    using AMDGPU;'

# Precompile DFTK as a check
RUN julia --project="/dftk_source/TestEnv" -e '\
    using Pkg; \
    Pkg.develop(path="/dftk_source"); \
    using DFTK;'