# Use and existing Julia image as a base
FROM docker.io/library/julia:1.12 AS builder

ENV JULIA_DEPOT_PATH=/opt/julia-depot

COPY . /dftk_source
WORKDIR /dftk_source

# Add CUDA and precompile DFTK
RUN julia --project="/dftk_source/TestEnv" -e '\
    using Pkg; \
    Pkg.add("CUDA"); \
    using CUDA; \
    CUDA.set_runtime_version!(v"13.0");'

# DFTKCUDAExt cannot be precompiled here, because NVIDIA drivers are lacking
RUN julia --project="/dftk_source/TestEnv" -e '\
    using Pkg; \
    Pkg.develop(path="/dftk_source"); \
    using DFTK;'