# Use and existing Julia image as a base
FROM docker.io/library/julia:1.12 AS builder

RUN mkdir -p /opt/cuda_cache
ENV JULIA_DEPOT_PATH=/opt/julia-depot
ENV CUDA_CACHE_PATH=/opt/cuda_cache

COPY . /dftk_source


# Add CUDA and precompile DFTK
RUN julia --project=TestEnv -e '\
    using Pkg; \
    Pkg.add("CUDA"); \
    using CUDA; \
    CUDA.set_runtime_version!(v"13.0");'

# DFTKCUDAExt cannot be precompiled here, because NVIDIA drivers are lacking
RUN julia --project=TestEnv -e '\
    using Pkg; \
    Pkg.develop(path="/dftk_source"); \
    using DFTK;'